# Use the official Ubuntu image 
FROM ubuntu:16.04

# Build image. eg:
# $ docker build -t runtimeverification/sol2iele:0.0.3 .
# Tag image to latest. eg:
# $ docker tag runtimeverification/sol2iele:0.0.3 runtimeverification/sol2iele:latest
# Publish image. eg:
# $ docker push runtimeverification/sol2iele:0.0.3
# $ docker push runtimeverification/sol2iele:latest
# Docker hub: https://hub.docker.com/r/runtimeverification/sol2iele/
MAINTAINER runtimeverification "contact@runtimeverification.com"

# TODO: Build IELE and Solidity to IELE Compiler.